TodayIHad.WebApp/Controllers/FoodsController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Reflection;
using System.Web.Mvc;
using TodayIHad.Domain.Entities;
using TodayIHad.Domain.Interfaces;
using TodayIHad.Repositories.Repositories;
using Database = TodayIHad.Repositories.Database;

namespace TodayIHad.WebApp.Controllers
{
    [Authorize]
    public class FoodsController : Controller
    {
        private Database db = new Database();
        private IUsersToFoodRepository _usersToFoodRepository = new UsersToFoodRepository();
        private IFoodRepository _foodRepository = new FoodRepository();
        private IFoodUnitRepository _foodUnitRepository = new FoodUnitRepository();


        // GET: Foods
        public ActionResult Index()
        {
            ViewBag.ListOfFoods  = _foodRepository.GetAllCreatedByCurrentUser().OrderByDescending(x => x.Id);

            return View();
        }

        // GET: Foods/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Food food = db.Foods.Find(id);
            if (food == null)
            {
                return HttpNotFound();
            }
            return View(food);
        }

        // GET: Foods/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Foods/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Calories,ProteinGr,FatGr,CarbsGr," +
                                                   "FiberGr,SugarGr,SodiumMg,FatSatGr,FatMonoGr," +
                                                   "FatPolyGr,CholesterolMg")] Food food, 
                                                    double gramsTotal, string foodUnits)
        {

            List<FoodUnit> foodUnitsList = JsonConvert.DeserializeObject<List<FoodUnit>>(foodUnits); 
            double hundredGramUnits = gramsTotal / 100;

            if (ModelState.IsValid)
            {

                List<PropertyInfo> filledInNutrients = food.GetType().GetProperties().Where(p=>p.PropertyType == typeof(double?)).Where(v=>v.GetValue(food) != null).ToList();

                foreach(var i in filledInNutrients)
                {
                    double value = Convert.ToDouble(i.GetValue(food));
                    double newValue = Math.Round((value / hundredGramUnits), 1, MidpointRounding.AwayFromZero);
                    i.SetValue(food, newValue);                    
                }

                _foodRepository.Create(food);
                _usersToFoodRepository.Create(food.Id);
                _foodUnitRepository.Create(foodUnitsList, food.Id);

                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        // GET: Foods/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Food food = db.Foods.Find(id);
            if (food == null)
            {
                return HttpNotFound();
            }

            return View(food);
        }

        // POST: Foods/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Calories,ProteinGr,FatGr,CarbsGr," + 
                                                 "FiberGr,SugarGr,SodiumMg,FatSatGr,FatMonoGr," + 
                                                 "FatPolyGr,CholesterolMg,IsDefault")] Food food, 
                                                 double gramsTotal, string foodUnits)
        {

            List<FoodUnit> foodUnitsList = JsonConvert.DeserializeObject<List<FoodUnit>>(foodUnits);
            double hundredGramUnits = gramsTotal / 100;

            if (ModelState.IsValid)
            {

                List<PropertyInfo> filledInNutrients = food.GetType().GetProperties().Where(p => p.PropertyType == typeof(double?)).Where(v => v.GetValue(food) != null).ToList();

                foreach (var i in filledInNutrients)
                {
                    double value = Convert.ToDouble(i.GetValue(food));
                    double newValue = Math.Round((value / hundredGramUnits), 1, MidpointRounding.AwayFromZero);
                    i.SetValue(food, newValue);
                }

                _foodRepository.Update(food);
                //_usersToFoodRepository.Create(food.Id);

                _foodUnitRepository.Delete(food.Id);
                _foodUnitRepository.Create(foodUnitsList, food.Id);

                return RedirectToAction("Index");
            }

            return View(food);

        }

        // GET: Foods/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Food food = db.Foods.Find(id);
            if (food == null)
            {
                return HttpNotFound();
            }
            return View(food);
        }

        // POST: Foods/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

            _usersToFoodRepository.Delete(id);
            _foodUnitRepository.Delete(id);
            _foodRepository.Delete(id);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult GetUnitsForFood(int foodId)
        {
            List<FoodUnit> foodUnitList = _foodUnitRepository.GetAllForCurrentFood(foodId);

            if (foodUnitList != null)
            {
                return Json(new { data = foodUnitList });
            }

            return Json(new { error = true });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TodayIHad.WebApp/Views/Foods/Create.cshtml
@model TodayIHad.Domain.Entities.Food

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-horizontal">
        <h4>Food</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Calories, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Calories, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Calories, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProteinGr, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProteinGr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProteinGr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FatGr, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FatGr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FatGr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CarbsGr, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CarbsGr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CarbsGr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FiberGr, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FiberGr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FiberGr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SugarGr, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SugarGr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SugarGr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SodiumMg, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SodiumMg, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SodiumMg, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FatSatGr, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FatSatGr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FatSatGr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FatMonoGr, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FatMonoGr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FatMonoGr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FatPolyGr, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FatPolyGr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FatPolyGr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CholesterolMg, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CholesterolMg, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CholesterolMg, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsDefault, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsDefault, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IsDefault, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TodayIHad.WebApp/Views/Foods/Delete.cshtml
@model TodayIHad.Domain.Entities.Food

@{
    ViewBag.Title = "Delete";
}

<h2>Delete "@Model.Name"?</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            Calories
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Calories)
        </dd>

        <dt>
            Protein
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProteinGr)
        </dd>

        <dt>
            Fat
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FatGr)
        </dd>

        <dt>
            Carbs
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CarbsGr)
        </dd>

        <dt>
            Fiber
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FiberGr)
        </dd>

        <dt>
            Sugar
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SugarGr)
        </dd>

        <dt>
            Sodium (mg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SodiumMg)
        </dd>

        <dt>
            Sat. Fat
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FatSatGr)
        </dd>

        <dt>
            Mono. Fat
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FatMonoGr)
        </dd>

        <dt>
            Poly. Fat
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FatPolyGr)
        </dd>

        <dt>
            Cholesterol (mg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CholesterolMg)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TodayIHad.WebApp/Views/Foods/Details.cshtml
@model TodayIHad.Domain.Entities.Food

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Food</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Calories)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Calories)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProteinGr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProteinGr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FatGr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FatGr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CarbsGr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CarbsGr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FiberGr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FiberGr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SugarGr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SugarGr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SodiumMg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SodiumMg)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FatSatGr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FatSatGr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FatMonoGr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FatMonoGr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FatPolyGr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FatPolyGr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CholesterolMg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CholesterolMg)
        </dd>



    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TodayIHad.WebApp/Views/Foods/Index.cshtml
@model TodayIHad.Domain.Entities.Food


@{
    ViewBag.Title = "Index";
}

<br />

<div class="userFoodContainer container">

    <h3>Create New Food - Step <span id="createFoodStepNum">1</span> of 2</h3>
    <br />

    @using (Html.BeginForm("Create", "Foods", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="userFoodForm form-group col-md-8">
            <div id="createFoodStep1">

                <div class="row form-group">
                    <div class="col-xs-12">
                        <label>Food Name <span class="required">*</span></label>
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @id = "userFoodName" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-xs-6">
                        <label>Amount</label>
                        <input type="number" value="100" id="userFoodAmount" class="form-control" />
                    </div>
                    <div id="foodUnitsContainer" class="col-xs-6">
                        <div class="row">
                            <label class="col-xs-6">Unit</label>
                            <a id="addUnit" href="#">Add Unit</a>

                        </div>
                        <select id="userFoodUnit" class="form-control" name="userFoodUnit">
                            <option id="optionGr" value="gr" data-gramweight="1" selected>gr</option>
                            <option id="optionOz" value="oz" data-gramweight="28.35">oz</option>
                        </select>

                    </div>
                </div>
                <div id="addUnitContainer"></div>

                <input type="hidden" id="gramsTotal" name="gramsTotal" value="100" />
                <input type="hidden" id="foodUnits" name="foodUnits" value="" />
                <div class="alert alert-danger" role="alert">All nutrient values should be per selected weight: <strong><span id="createFoodPerAmount">100 x gr or 100 grams.</span></strong></div>


                <div class="row form-group">
                    <div class="col-xs-6">
                        <label>Calories <span class="required">*</span></label>
                        @Html.EditorFor(model => model.Calories, new
                   {
                       htmlAttributes = new
                       {
                           @class = "form-control",
                           @id = "userFoodCalories",
                           @type = "number",
                           @data_val_number = "Calories must be between 0 and 99999",
                           @placeholder = 0
                       }
                   })
                        @Html.ValidationMessageFor(model => model.Calories, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-xs-6">
                        <label>Protein (g) <span class="required">*</span></label>
                        @Html.EditorFor(model => model.ProteinGr, new
                   {
                       htmlAttributes = new
                       {
                           @class = "form-control",
                           @id = "userFoodProtein",
                           @type = "number",
                           @data_val_number = "Protein must be between 0 and 99999",
                           @placeholder = 0
                       }
                   })
                        @Html.ValidationMessageFor(model => model.ProteinGr, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col-xs-6">
                        <label>Fat (g) <span class="required">*</span></label>
                        @Html.EditorFor(model => model.FatGr, new
                   {
                       htmlAttributes = new
                       {
                           @class = "form-control",
                           @id = "userFoodFat",
                           @type = "number",
                           @data_val_number = "Fat must be between 0 and 99999",
                           @placeholder = 0
                       }
                   })
                        @Html.ValidationMessageFor(model => model.FatGr, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-xs-6">
                        <label>Carbs (g) <span class="required">*</span></label>
                        @Html.EditorFor(model => model.CarbsGr, new
                   {
                       htmlAttributes = new
                       {
                           @class = "form-control",
                           @id = "userFoodCarbs",
                           @type = "number",
                           @data_val_number = "Carbs must be between 0 and 99999",
                           @placeholder = 0
                       }
                   })
                        @Html.ValidationMessageFor(model => model.CarbsGr, "", new { @class = "text-danger" })
                    </div>
                </div>

                <button id="continueBtn" class="btn btn-info"> Continue</button>

            </div>

            <div id="createFoodStep2">

                <div class="alert alert-info" role="alert"> <strong>Optional fields.</strong> Try to fill them in for better accuracy.</div>

                <div class="row form-group">
                    <div class="col-xs-6">
                        <label>Saturated Fat (g)</label>
                        @Html.EditorFor(model => model.FatSatGr, new
                   {
                       htmlAttributes = new
                       {
                           @class = "form-control",
                           @id = "userFoodFatSat",
                           @type = "number",
                           @data_val_number = "Sat. Fat must be between 0 and 99999",
                           @placeholder = 0
                       }
                   })
                        @Html.ValidationMessageFor(model => model.FatSatGr, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-xs-6">
                        <label>Fiber (g)</label>
                        @Html.EditorFor(model => model.FiberGr, new
                   {
                       htmlAttributes = new
                       {
                           @class = "form-control",
                           @id = "userFoodFiber",
                           @type = "number",
                           @data_val_number = "Fiber must be between 0 and 99999",
                           @placeholder = 0
                       }
                   })
                        @Html.ValidationMessageFor(model => model.FiberGr, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col-xs-6">
                        <label>Mono. Fat (g)</label>
                        @Html.EditorFor(model => model.FatMonoGr, new
                   {
                       htmlAttributes = new
                       {
                           @class = "form-control",
                           @id = "userFoodFatMono",
                           @type = "number",
                           @data_val_number = "Mono. Fat must be between 0 and 99999",
                           @placeholder = 0
                       }
                   })
                        @Html.ValidationMessageFor(model => model.FatMonoGr, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-xs-6">
                        <label>Sugar (g)</label>
                        @Html.EditorFor(model => model.SugarGr, new
                   {
                       htmlAttributes = new
                       {
                           @class = "form-control",
                           @id = "userFoodSugar",
                           @type = "number",
                           @data_val_number = "Sugar must be between 0 and 99999",
                           @placeholder = 0
                       }
                   })
                        @Html.ValidationMessageFor(model => model.SugarGr, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col-xs-6">
                        <label>Poly. Fat (g)</label>
                        @Html.EditorFor(model => model.FatPolyGr, new
                   {
                       htmlAttributes = new
                       {
                           @class = "form-control",
                           @id = "userFoodFatPoly",
                           @type = "number",
                           @data_val_number = "Poly. Fat must be between 0 and 99999",
                           @placeholder = 0
                       }
                   })
                        @Html.ValidationMessageFor(model => model.FatPolyGr, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-xs-6">
                        <label>Sodium (mg)</label>
                        @Html.EditorFor(model => model.SodiumMg, new
                   {
                       htmlAttributes = new
                       {
                           @class = "form-control",
                           @id = "userFoodSodium",
                           @type = "number",
                           @data_val_number = "Sodium must be between 0 and 99999",
                           @placeholder = 0
                       }
                   })
                        @Html.ValidationMessageFor(model => model.SodiumMg, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col-xs-6">
                        <label>Cholesterol (mg)</label>
                        @Html.EditorFor(model => model.CholesterolMg, new
                   {
                       htmlAttributes = new
                       {
                           @class = "form-control",
                           @id = "userFoodCholes",
                           @type = "number",
                           @data_val_number = "Cholesterol must be between 0 and 99999",
                           @placeholder = 0
                       }
                   })
                        @Html.ValidationMessageFor(model => model.CholesterolMg, "", new { @class = "text-danger" })
                    </div>

                </div>
                <div class="form-group">
                    <input type="submit" id="createFoodBtn" value="Create Food" class="btn btn-success" />
                    <button id="backBtnCreateFood" class="btn btn-default">Back to Step 1</button>
                    <button id="cancelBtnCreateFood" class="btn btn-default">Cancel</button>
                </div>
            </div>
        </div>
    }


</div>
<br /><br />


<div id="userFoodList" class="col-md-8">
    <h3>My Foods</h3>

    <table class="table">
        @foreach (var item in ViewBag.ListOfFoods)
            {
            <tr>
                <td>
                    <a href="@Url.Action("Edit/"+@item.Id)">@item.Name</a>
                </td>
                <td class="actionContainerMyFoods">
                    <a href="@Url.Action("Delete/"+@item.Id)"><span class="glyphicon glyphicon-trash"></span></a>
                </td>
            </tr>
        }
    </table>
</div>

<script id="addFoodUnitTemplate" type="text/mustachetemplates">
    <div id="addFoodUnit" class="row form-group cardShadow">

        <div id="headerAddUnit" class="row form-group col-xs-12">

            <div class="col-xs-10 cardLabelRed" id="addNewUnitHeading">
                <div>
                    Add or remove units
                </div>
            </div>
            <div class="closeBtnContainer">
                <button id="closeBtnAddUnit" class="glyphicon glyphicon-remove btn btn-default"></button>
            </div>
        </div>

        <div id="unitList" class="col-xs-12 col-md-6">
            <label>Your  units</label>
            <table id="addUnitTable" class="table table-condensed">
                {{#unitsArray}}
                <tr>
                    <td class="col-xs-2"><input type='checkbox' name='checkboxUnit' id='{{Id}}'></td>
                    <td class="col-xs-7" id='nameUnit'> {{Name}} </td>
                    <td class="col-xs-3" id='weightInGramsUnit'> {{GramWeight}}  g</td>
                </tr>
                {{/unitsArray}}
            </table>
        </div>
        <div id="actionContainerAddUnit" class="col-xs-12 col-md-6">

            <label>Name</label>
            <input type="text" id="nameAddUnit" class="form-control" placeholder="e.g. - slice, cup..." />

            <label>Weight in grams</label>
            <input type="number" id="weightInGramsAddUnit" class="form-control" placeholder="0" />

        </div>

        <div id="unitBtnContainer" class="row col-xs-12">
            <input type="button" id="deleteUnitBtn" class="btn btn-danger" value="Delete Selected" />
            <input type="button" id="addUnitBtn" class="btn btn-success " value="Add Unit" />
        </div>
    </div>




</script>